/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PI6jx9dWcbp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function BuildMenu() {
  return (
    <div className="flex flex-col h-screen">
      <main className="flex-1 bg-[url(/placeholder.svg)] bg-cover bg-center">
        <div className="h-full flex items-center justify-center">
          <div className="bg-white/80 backdrop-blur-sm p-8 rounded-lg shadow-lg">
            <h1 className="text-3xl font-bold mb-4">Bienvenido al juego</h1>
            <p className="text-lg mb-8">Comienza a construir tu ciudad.</p>
            <div className="flex justify-center">
              <Button>Comenzar</Button>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-gray-900 text-white p-6">
        <div className="container mx-auto grid grid-cols-3 gap-4">
          <div className="flex flex-col items-center">
            <img
              alt="Building 1"
              height={80}
              src=""
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width={80}
            />
            <span className="text-sm font-medium mt-2">Edificio 1</span>
            <span className="text-sm text-gray-400">$100</span>
          </div>
          <div className="flex flex-col items-center">
            <img
              alt="Building 2"
              height={80}
              src=""
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width={80}
            />
            <span className="text-sm font-medium mt-2">Edificio 2</span>
            <span className="text-sm text-gray-400">$150</span>
          </div>
          <div className="flex flex-col items-center">
            <img
              alt="Building 3"
              height={80}
              src=""
              style={{
                aspectRatio: "80/80",
                objectFit: "cover",
              }}
              width={80}
            />
            <span className="text-sm font-medium mt-2">Edificio 3</span>
            <span className="text-sm text-gray-400">$200</span>
          </div>
          <div className="flex justify-center">
            <Button>
              <PlusIcon className="w-5 h-5 mr-2" />
              Construir
            </Button>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default BuildMenu;

function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
